### ISSUE TITLE
MSVC_VERSION not set

### ISSUE THREAD

**Issue by mickae1** [MarkSchofield/WindowsToolchain#103]
Hi, 
How can I debug that MSVC_VERSION is not set ?
other variable like CMAKE_C_COMPILER are set correctly
( visual studio 2022 )

thx you,

**Comment by mickae1** [comment]
ok, i'm debuging, I found that VSWHERE_PROPERTY is empty

**Comment by MarkSchofield** [comment]
What version/commit of WindowsToolchain are you using? What version of CMake are you using? #91 changed the behavior for `MSVC_VERSION` in the WindowsToolchain implementation - the WindowsToolchain was originally setting it, but in setting it, the CMake scripts weren't setting _other_ version variables. In my testing *not* setting `MSVC_VERSION` in the toolchain, caused CMake to set a full set of variables.

Using VSCode's support for debugging CMake is a great way to debug things - details [here](https://devblogs.microsoft.com/cppblog/introducing-cmake-debugger-in-vs-code-debug-your-cmake-scripts-using-open-source-cmake-debugger/). Alternatively, running cmake configuration with [the "--trace" command](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-trace) to see if `MSVC_VERSION` is ever set, would perhaps be a good way to start debugging.

**Comment by MarkSchofield** [comment]
As of #91, setting MSVC_VERSION is done by the main CMake logic. So, I don't believe there's anything in this Toolchain that could causing it not to be set. If you have specific repro steps, feel free to re-activate. I hope you figured it out!
