### ISSUE TITLE
Request: Code Coverage

### ISSUE THREAD

**Issue by aboelens** [MarkSchofield/WindowsToolchain#113]
I have a feature request. I think it would be great to also have code coverage available using llvm-cov. Do you think this would be a useful addition to this project?

**Comment by MarkSchofield** [comment]
In order to keep 'WindowsToolchain' focused, I want to keep it to only things that a toolchain can do - or needs to do. I _think_ code coverage through llvm-cov can probably configured independently - is there anything toolchain specific that needs to be done?
