### ISSUE TITLE
Could not find NMAKE using the following names: nmake

### ISSUE THREAD

**Issue by aboelens** [MarkSchofield/WindowsToolchain#114]
Installing openssl using vcpkg and the Windows.MSVC.toolchain.cmake I get the following error message:

CMake Error at scripts/cmake/vcpkg_build_nmake.cmake:43 (find_program):
  Could not find NMAKE using the following names: nmake

cmake looks in:

CMake Debug Log at scripts/cmake/vcpkg_build_nmake.cmake:43 (find_program):
  find_program called with the following settings:

    VAR: NMAKE
    NAMES: "nmake"
    Documentation: Path to a program.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 1
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1
    CMAKE_FIND_USE_INSTALL_PREFIX: 1

  find_program considered the following locations:

    C:/Program Files/PowerShell/7/nmake.com
    C:/Program Files/PowerShell/7/nmake.exe
    C:/Program Files/PowerShell/7/nmake
    C:/Windows/System32/nmake.com
    C:/Windows/System32/nmake.exe
    C:/Windows/System32/nmake
    C:/Windows/nmake.com
    C:/Windows/nmake.exe
    C:/Windows/nmake
    C:/Windows/System32/wbem/nmake.com
    C:/Windows/System32/wbem/nmake.exe
    C:/Windows/System32/wbem/nmake
    C:/Windows/System32/WindowsPowerShell/v1.0/nmake.com
    C:/Windows/System32/WindowsPowerShell/v1.0/nmake.exe
    C:/Windows/System32/WindowsPowerShell/v1.0/nmake
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/nmake.com
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/nmake.exe
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/nmake
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/ninja/1.10.2-windows/nmake.com
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/ninja/1.10.2-windows/nmake.exe
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/ninja/1.10.2-windows/nmake
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/nasm/nasm-2.16.01/nmake.com
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/nasm/nasm-2.16.01/nmake.exe
    C:/Users/A879833/AppData/Local/vcpkg/downloads/tools/nasm/nasm-2.16.01/nmake

  The item was not found.

The right version is in:

"C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/"

which is equivalent to

"${VS_TOOLSET_PATH}/bin/Host${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}/${CMAKE_VS_PLATFORM_TOOLSET_ARCHITECTURE}/"

is it possible to export e.g. CMAKE_PROGRAM_PATH from the toolchain, so the right version of nmake can be found?

**Comment by MarkSchofield** [comment]
It's not clear to me what the 'right thing' to do is: should a toolchain update `CMAKE_PROGRAM_PATH`, or should it just have documented properties it sets, to allow consumers to update `CMAKE_PROGRAM_PATH` if they want to..? #99 would benefit from a documented path to VS.

**Comment by aboelens** [comment]
For programs that are always at a fixed location, it makes sense to me to let the user set CMAKE_PROGRAM_PATH. However, in the case of nmake, the path changes depending on the compiler that is used, which is set by the toolchain.

**********************************************************************

This transmission is confidential and must not be used or disclosed by anyone other than the intended recipient. Neither Tata Steel Europe Limited nor any of its subsidiaries can accept any responsibility for any use or misuse of the transmission by anyone.

For address and company registration details of certain entities within the Tata Steel Europe group of companies, please visit https://www.tatasteeleurope.com/en/legal-notice/entities

**********************************************************************


Sensitivity: general

**Comment by MarkSchofield** [comment]
Fixed with #119.
