### ISSUE TITLE
Add additional languages to CMAKE_<LANG>_STANDARD_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by waldnercharles** [MarkSchofield/WindowsToolchain#115]
I ran into an issue while compiling SDL. The Windows assembler couldn't find a necessary .inc file that was in the Windows SDK include path. At closer inspection, the path wasn't being included for ASM_MASM. Adding it to the loop seems to fix the issue.

Figured I'd open an issue before making a PR in case other languages should be added as well.

**Comment by MarkSchofield** [comment]
Sounds good. There's a few "ASM" variants listed on [the documentation for `enable_language`](https://cmake.org/cmake/help/latest/command/enable_language.html#enable-language): "ASM", "ASM_MASM", "ASM_NASM" and "ASM_MARMASM", I think all would be needed...?!

**Comment by MarkSchofield** [comment]
I think this has been fixed but with #117, but I'll hold off on closing until I've completed #118.
