### ISSUE TITLE
CMAKE_CROSSCOMPILING should not be true by default

### ISSUE THREAD

**Issue by aboelens** [MarkSchofield/WindowsToolchain#123]
When compiling for the host platform and architecture I don't think CMAKE_CROSSCOMPILING should be set to true.

https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html

I ran into a bug where depending on whether one is cross compiling, Qt looks for a "bat" or "exe" extension. The wrong extension was selected because CMAKE_CROSSCOMPILING is set to true by default in the toolchain, even though I was not cross compiling.

**Comment by aboelens** [comment]
Just looked at the code and it looks good to me. I assume you are not planning on supporting something like WindowsStore? It that case you'd also have to compare CMAKE_SYSTEM_NAME with CMAKE_HOST_SYSTEM_NAME.

**Comment by MarkSchofield** [comment]
> Just looked at the code and it looks good to me. I assume you are not planning on supporting something like WindowsStore? It that case you'd also have to compare CMAKE_SYSTEM_NAME with CMAKE_HOST_SYSTEM_NAME.

I don't think so right now. If there's feedback that wants support, then that can be a separate task. But right now, the toolchain is just for 'Windows' systems. Thanks for calling this out!
