### ISSUE TITLE
Stable release version requested

### ISSUE THREAD

**Issue by ClausKlein** [MarkSchofield/WindowsToolchain#43]
To use Toolchain with FetchContent we need a taged version

**Comment by MarkSchofield** [comment]
I'm happy to make a release, but I don't think it would be 'stable' per se. There's still cleanup and file movement that needs to happen to address the feedback in #18. And I've been wanting to rename the repo from 'Toolchain' to 'WindowsToolchain' to be a bit more specific. Let me work on the rename and the release...

**Comment by MarkSchofield** [comment]
Release [v0.5.0](https://github.com/MarkSchofield/WindowsToolchain/releases/tag/v0.5.0) created.
