### ISSUE TITLE
Standalone MSVC toolchain

### ISSUE THREAD

**Issue by CallistoM** [MarkSchofield/WindowsToolchain#55]
Is it possible to use the toolchain as a standalone toolchain ie; no Visual Studio installed? CMake does allow variable: CMAKE_GENERATOR_INSTANCE to select an instance.

**Comment by MarkSchofield** [comment]
The toolchain works with the "Build Tools for Visual Studio 2022" - that you can find here:

    https://visualstudio.microsoft.com/downloads/

That's the minimal installation that should work. In addition to the build tools, you'll also need a Windows SDK that you download from here:

    https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

Install those two things and the Toolchain should find them and hook them up.

**Comment by MarkSchofield** [comment]
Let me know how it goes! I should perhaps write up a getting started guide for this scenario.

**Comment by CallistoM** [comment]
I tried to use Build Tools for Visual Studio 2022 with CMAKE_GENERATOR_INSTANCE but CMake refuses to use a custom location ie; C:/BuildTools for example. I don't think this is the portable solution I am looking for, unless it's somehow possible with this toolchain to use a different location then vswhere.exe gives.
