### ISSUE TITLE
Wrap add_compile_options options into $<$<COMPILE_LANGUAGE:CXX>:option>

### ISSUE THREAD

**Issue by bebuch** [MarkSchofield/WindowsToolchain#70]
```cmake
# Module support
if(VS_EXPERIMENTAL_MODULE)
    add_compile_options(/experimental:module)
    add_compile_options(/stdIfcDir "${VS_TOOLSET_PATH}/ifc/${CMAKE_VS_PLATFORM_TOOLSET_ARCHITECTURE}")
endif()
```

These options are forwareded to all compilers, including the NASM assambler in my case. Wrapping the options into a language specific generator expression should solve the problem.

```cmake
# Module support
if(VS_EXPERIMENTAL_MODULE)
    add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/experimental:module>)
    add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/stdIfcDir> $<$<COMPILE_LANGUAGE:CXX>:"${VS_TOOLSET_PATH}/ifc/${CMAKE_VS_PLATFORM_TOOLSET_ARCHITECTURE}">)
endif()
```

**Comment by MarkSchofield** [comment]
Thanks! I _think_ I should actually be using [`CMAKE_CXX_FLAGS_INIT`](https://cmake.org/cmake/help/v3.26/variable/CMAKE_LANG_FLAGS_INIT.html).

**Comment by bebuch** [comment]
I adjusted my own toolchain to use `CMAKE_CXX_FLAGS_INIT` instead and it worked as expected. Looks to be the right solution. ;-)
