### ISSUE TITLE
How to specify toolset?

### ISSUE THREAD

**Issue by Jihadist** [MarkSchofield/WindowsToolchain#81]
Hello! How to specify toolset correctly? For visual studio generator I can paste only few strings in CMakePresets and it targets correctly
For example:
```
        "toolset": {
          "value": "v120_xp,host=x64",
          "strategy": "external"
        },
```
But I have no ideas how to do it with `WindowsToolchain`

**Comment by kaloth** [comment]
I think the problem here will be that the toolsets are a feature of MSBuild and are implemented via MSBuild configuration XML files. We'd have to replicate the same compiler/linker configuration in a CMake/Ninja friendly way.

This is something that I've done for my own projects but it's not simple and certainly not easy to guarantee the same settings as MSBuild without a lot of complexity.

**Comment by MarkSchofield** [comment]
There's documentation at the top of the [`Windows.MSVC.toolchain.cmake`](https://github.com/MarkSchofield/WindowsToolchain/blob/main/Windows.MSVC.toolchain.cmake) file that explain which properties control behavior. To set the host to be x64, you'd need `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE` to be `x64`. TBH, I'm not sure what `v120_xp` corresponds to; if I install the "C++ Windows XP Support for VS 2017 (v141) tools" on my VS2022 Community install, then it installs the '14.16.27023' toolset, which you'd get by specifying `VS_PLATFORM_TOOLSET_VERSION` to be `14.16.27023`. Note that I just fixed a bug (#78) in specifying the toolset version via `VS_PLATFORM_TOOLSET_VERSION`, so you'd need a build from the main branch.

**Comment by xakod** [comment]
@MarkSchofield thank you! v120_xp corresponds to 12.0.40629.0 but I'm not sure it's correct.

**Comment by lili2012** [comment]
my win10 system visual studio 2022 install two toolset under this folder: 

> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133
and
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207

you could reference this to know toolset version number: 

> https://github.com/KirillOsenkov/MSBuildTools/blob/main/msvc_toolset_cheatsheet.md

the following cacheVariables could let ninja use vs2019 toolset:
```
"cacheVariables": {
    "VS_PLATFORM_TOOLSET_VERSION":"14.29.30133",
    "VCPKG_CHAINLOAD_TOOLCHAIN_FILE": "${sourceDir}/../WindowsToolchain/Windows.MSVC.toolchain.cmake",
    "CMAKE_TOOLCHAIN_FILE": "${sourceDir}/../../vcpkg/scripts/buildsystems/vcpkg.cmake"
}
```
